# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Takeoff - Documentation
email: info@statik.be
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
destination: jekyll-dist
source: jekyll
exclude: ['takeoff', 'Gruntfile.js', 'package.json']
